import {
  AddressBook,
  ArticleNyTimes,
  Book,
  BookmarkSimple,
  BookOpenText,
  BookOpenUser,
  Books,
  Chalkboard,
  ChalkboardTeacher,
  ChatCircleText,
  CircleNotch,
  DeviceMobile,
  Exam,
  Faders,
  File,
  GearSix,
  GraduationCap,
  IdentificationCard,
  LineSegments,
  ListChecks,
  ListMagnifyingGlass,
  Notification,
  QuestionMark,
  Student,
  UserGear,
  UsersThree,
  Video,
} from '@phosphor-icons/react';
import type { Icon } from '@phosphor-icons/react/dist/lib/types';
import { At, ChalkboardSimple, Path, Table } from '@phosphor-icons/react/dist/ssr';
import { ChartPie as ChartPieIcon } from '@phosphor-icons/react/dist/ssr/ChartPie';
import { GearSix as GearSixIcon } from '@phosphor-icons/react/dist/ssr/GearSix';
import { PlugsConnected as PlugsConnectedIcon } from '@phosphor-icons/react/dist/ssr/PlugsConnected';
import { User as UserIcon } from '@phosphor-icons/react/dist/ssr/User';
import { Users as UsersIcon } from '@phosphor-icons/react/dist/ssr/Users';
import { XSquare } from '@phosphor-icons/react/dist/ssr/XSquare';

export const navIcons = {
  'chart-pie': ChartPieIcon,
  'gear-six': GearSixIcon,
  'plugs-connected': PlugsConnectedIcon,
  'x-square': XSquare,
  user: UserIcon,
  users: UsersIcon,
  'chalkboard-simple': ChalkboardSimple,
  quiz: File,
  question: QuestionMark,
  form: Table,
  system: Faders,
  email: At,
  notification: Notification,
  roles: AddressBook,
  path: Path,
  course: Books,
  lesson: Video,
  student: Student,
  setting: GearSix,
  userManager: UserGear,
  book: Book,
  class: Chalkboard,
  test: Exam,
  chat: ChatCircleText,
  teacher: ChalkboardTeacher,
  answer: ArticleNyTimes,
  progress: CircleNotch,
  userPath: LineSegments,
  userCourse: BookOpenText,
  userLesson: BookOpenUser,
  userClass: GraduationCap,
  userQuiz: ListChecks,
  liveQuizTracking: ListMagnifyingGlass,
  criteria: UsersThree,
  category: BookmarkSimple,
  employee: IdentificationCard,
  devices: DeviceMobile,
  files: File,
  bookUser: BookOpenUser,
} as Record<string, Icon>;
