export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/management/customers',
    users: '/dashboard/management/users',
    roles: '/dashboard/management/roles',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    class: '/dashboard/class',
    quiz: '/dashboard/quiz',
    question: '/dashboard/questions',
    form: '/dashboard/form',
    system: '/dashboard/system',
    email: '/dashboard/email',
    notification: '/dashboard/notification',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
