export const paths = {
  home: '/dashboard/courses/courses',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard/courses/courses',
    account: '/dashboard/system/account',
    customers: '/dashboard/management/customers',
    users: '/dashboard/management/users',
    roles: '/dashboard/management/roles',
    criteria: '/dashboard/management/criteria',
    employee: '/dashboard/management/employee',
    category: '/dashboard/management/category',
    devices: '/dashboard/management/devices',
    integrations: '/dashboard/system/integrations',
    settings: '/dashboard/system/settings',
    class: '/dashboard/class/class',
    teacher: '/dashboard/class/teacher',
    attendance: '/dashboard/class/attendance',
    quiz: '/dashboard/quiz/quiz',
    question: '/dashboard/quiz/questions',
    answers: '/dashboard/quiz/answers',
    form: '/dashboard/management/form',
    system: '/dashboard/system/system',
    email: '/dashboard/system/email',
    notification: '/dashboard/system/notification',
    courses: '/dashboard/courses/courses',
    path: '/dashboard/courses/path',
    lesson: '/dashboard/courses/lesson',
    userPathProgress: '/dashboard/progress/path',
    userCourseProgress: '/dashboard/progress/course',
    userLessonProgress: '/dashboard/progress/lesson',
    userQuizProgress: '/dashboard/progress/quiz',
    liveQuizTracking: '/dashboard/progress/quiz-live',
    userClassProgress: '/dashboard/progress/class',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
