export const paths = {
  home: '/dashboard/modular/courses',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard/modular/courses',
    account: '/dashboard/system/account',
    customers: '/dashboard/management/customers',
    users: '/dashboard/management/users',
    roles: '/dashboard/management/roles',
    criteria: '/dashboard/management/criteria',
    employee: '/dashboard/management/employee',
    category: '/dashboard/management/category',
    devices: '/dashboard/management/devices',
    integrations: '/dashboard/system/integrations',
    settings: '/dashboard/system/settings',
    class: '/dashboard/class/classes',
    teacher: '/dashboard/class/teacher',
    attendance: '/dashboard/class/attendance',
    quiz: '/dashboard/quiz/quiz',
    exam: '/dashboard/exam/exam',
    quizEnroll: '/dashboard/quiz/enroll',
    examEnroll: '/dashboard/exam/enroll',
    question: '/dashboard/questions/questions',
    questionCategory: '/dashboard/questions/category',
    answers: '/dashboard/questions/answers',
    form: '/dashboard/management/form',
    system: '/dashboard/system/system',
    email: '/dashboard/system/email',
    notification: '/dashboard/system/notification',
    courses: '/dashboard/modular/courses',
    courseLesson: '/dashboard/modular/lesson',
    path: '/dashboard/modular/path',
    lesson: '/dashboard/linear/lesson',
    lessonCourse: '/dashboard/linear/courses',
    userPathProgress: '/dashboard/progress/path',
    userCourseProgress: '/dashboard/modular/progress',
    userCourseProgressCreate: '/dashboard/modular/enroll',
    userLessonProgress: '/dashboard/linear/progress',
    userLessonProgressCreate: '/dashboard/linear/enroll',
    userQuizProgress: '/dashboard/quiz/progress',
    userExamProgress: '/dashboard/exam/progress',
    liveQuizTracking: '/dashboard/progress/quiz-live',
    userClassProgress: '/dashboard/progress/class',
    resources: '/dashboard/system/resources',
    reportCourse: '/dashboard/report/course',
    reportLesson: '/dashboard/report/lesson',
    reportExam: '/dashboard/report/exam',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
